spring.application.name=learnJwtAuth

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=akash123
spring.datasource.driver-class-name=org.h2.Driver

jwt.secret=rHYd0BN9N8YFyWUIw5kTD133TxOPSONS2vA8v3RGy6C
jwt.expiration=86400000
